clc;
clear all;
close all;
fs=4000; Channels=1;bits=16;
r=audiorecorder(fs,bits,Channels);
duration=5; disp('Recording Started');
recordblocking(r,duration);
disp('Recording Stopped');
x=getaudiodata(r);
sound(x,fs,bits);
t=0:1/fs:(length(x)-1)/fs;
subplot(2,1,1); 
plot(t,x,'Linewidth',1.5);
xlabel('time(sec)'); ylabel('Amplitude');
title('Time domain plot of the recorded signal');
n=length(x);
f=0:(n-1)*fs/n;
y=fft(x,n);
f_0=(-n/2:n/2-1).*(fs/n);
y_0=fftshift(y);
ay_0=abs(y_0);
subplot(2,1,2);
plot(f_0,ay_0,'Linewidth',1.5);
xlabel('Frequency (Hz)');
ylabel('Amplitude');
title('Frequency domain plot of audio signal');
filename='myvoice.wav';
audiowrite(filename,x,fs);
